apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: webapp-k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: webapp-k8s-multi.com
  dnsNames:
    - webapp-k8s-multi.com
    - www.webapp-k8s-multi.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - webapp-k8s-multi.com
          - www.webapp-k8s-multi.com
